### PR TITLE
Remove pyyaml workaround.

### LINKED ISSUE #18: PyYAML warnings on install
This is a PyYAML problem (not our fault). Fixed in https://github.com/yaml/pyyaml/commit/298e07907ae526594069f6fdf31f2f1278cc1ae3

So we just have to wait for PyYAML 3.13 to be released with this fix included

### PR DESCRIPTION
**Pull request by AndreasAlbert**
Require pyyaml version > 4 to avoid the issue described in #18 and remove the travis workaround.

Closes #18

### CODE REVIEW

**Comment by clelange** [comment]
Did you try this with a CMSSW setup? And if so, we should add instructions to make sure people can use it on lxplus.

**Comment by AndreasAlbert** [comment]
Yes, I tested it with `CMSSW_10_2_3` and it seems to work for me pretty easily. I added a recipe to the documentation.

**Comment by AndreasAlbert** [comment]
(That means that I can install the library and run the tests successfully)

**Comment by clelange** [comment]
I rebased this to `master` to see how python3 copes with the forced pyyaml version, will approve once tests have run successfully.

**Pull request merged**
