### PR TITLE
Getting started

### PR DESCRIPTION
**Pull request by clelange**
Adding a notebook to create a submission with a simple plot without uncertainties.

For testing of this PR, you need to use this binder link:

[Binder](https://mybinder.org/v2/gh/clelange/hepdata_lib/getting_started?filepath=examples/Getting_started.ipynb)

### CODE REVIEW

**Comment by clelange** [comment]
I just realised that I need to convert the abstract to LateX, but that's a detail. I'll get to it now.

**Comment by clelange** [comment]
btw, shall we move the notebooks to a subdirectory (e.g. `notebooks` or `examples`, which name do you prefer?) since they don't have anything to do with the library.

**Comment by clelange** [comment]
This is the first step towards #40

**Comment by AndreasAlbert** [comment]
Let's put them in `examples`, that's more self-explanatory

**Comment by clelange** [comment]
This should be ready for squash and merge!
We still need examples for reading TGraph, but now we have
- text files
- histograms
- combine ntuples

**Pull request merged**
