### PR TITLE
Add test infrastructure.

### PR DESCRIPTION
**Pull request by AndreasAlbert**
Testing implemented as described [here](https://python-packaging.readthedocs.io/en/latest/testing.html)

**What works:** Running the test manually by installing the `nose` package and calling `nosetests` inside the main directory of the package

**What does not work:** Calling `python setup.py test`, which crashes after successfully running the tests with some technical problem in `ROOT.py`:
```
running test
running egg_info
writing requirements to hepdata_lib.egg-info/requires.txt
writing hepdata_lib.egg-info/PKG-INFO
writing top-level names to hepdata_lib.egg-info/top_level.txt
writing dependency_links to hepdata_lib.egg-info/dependency_links.txt
reading manifest file 'hepdata_lib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'hepdata_lib.egg-info/SOURCES.txt'
running build_ext
test_scale_values (hepdata_lib.test.test_uncertainty.TestUncertainty)
Test behavior of Uncertainty.scale_values function ... ok
test_scale_values (hepdata_lib.test.test_variable.TestVariable)
Test behavior of Variable.scale_values function ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.435s

OK
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/albert/software/root/lib/ROOT.py", line 632, in cleanup
    facade = sys.modules[ __name__ ]
KeyError: 'ROOT'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/albert/software/root/lib/ROOT.py", line 632, in cleanup
    facade = sys.modules[ __name__ ]
KeyError: 'ROOT'
```

### CODE REVIEW

**Comment by AndreasAlbert** [comment]
Ready to be merged IMO

**Comment by clelange** [comment]
Works in both python versions now, but I get a weird error at the end of the successful tests:
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-ikhhed/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/lcg/root/6.06.00-ikhhed4/lib/ROOT.py", line 590, in cleanup
    facade = sys.modules[ __name__ ]
KeyError: 'ROOT'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/external/python/2.7.11-ikhhed/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/lcg/root/6.06.00-ikhhed4/lib/ROOT.py", line 590, in cleanup
    facade = sys.modules[ __name__ ]
KeyError: 'ROOT'
```

@AndreasAlbert Do you get the same?

**Comment by AndreasAlbert** [comment]
@clelange: That was the problem I tried to in 3ce8512344de75f946d64443484cf640c2cfc818

If I use a fancy package for running the tests (`nose` in my case, `pytest` in your case), it produces the error you are getting. A way around this was to not use a fancy package, which still works fine. `python setup.py test` still works out-of-the-box, but you need to keep the `__init__.py` for that.

**Comment by clelange** [comment]
The little import statement fixes the problem.

**Pull request merged**
